### ISSUE TITLE
Unable to identify component: Malformed Maven component with item path

### ISSUE THREAD

**Issue by SimunKaracic** [sbt/sbt-ci-release#199]
I'm following the documentation and trying to publish an sbt plugin. 
Github action completes successfully when I push a tag, but the artifacts don't show up on sonatype or maven central.
I can find the builds in sonatype releases, and there I see only one problem: 
when I click on e.g. `sbt-kanela-runner-play-2.6-2.0.10.14-javadoc.jar` i see the following under `Component info`:
```Unable to identify component: Malformed Maven component with item path io/kamon/sbt-kanela-runner-play-2.6_2.12_1.0/2.0.10.14/sbt-kanela-runner-play-2.6-2.0.10.14-javadoc.jar.```

No other errors are visible in the whole build process.

Any hints on what I might be doing wrong, or where to find a more specific error message?

![image](https://user-images.githubusercontent.com/13893057/121010118-4b298980-c795-11eb-869d-2b9cdf5ec15f.png)

**Comment by SethTisue** [comment]
I suggest we close this ticket, as I doubt it's actionable in this repo. It looks like a Sonatype issue.
