### ISSUE TITLE
Unable to publish to subgroup

### ISSUE THREAD

**Issue by hughsimpson** [sbt/sbt-ci-release#220]
I've registered a group through sonatype (com.$company) which I can publish to, but I'm unable to publish to a subgroup (com.$company.$thingy). I'm not 100% clear if this is an issue with the plugin, with sonatype, or if I've just failed to perform some manual step that would permit it, but figured raising an issue here was the sanest way to establish which of these three is likely...

i.e. if I set `organization := "com.myCompany"` everything is kosher, but if I set `organization := "com.myCompany.lib"` I get an error `[MISSING_PROFILE] Profile com.myCompany.lib is not found. Check your sonatypeProfileName setting in build.sbt`

**Comment by olafurpg** [comment]
Thank you for reporting! I’m not familiar with how sonatype profiles work. You may need to open an issue with Sonatype OSS to allow publishing from the subdomain. I’d also recommend searching through issues on the sbt-sonatype repo. This plugin doesn’t do the actual releasing, it’s a thin wrapper over other plugins.

**Comment by hughsimpson** [comment]
Turned out I just had to set `sonatypeProfileName` in the module settings (rather than under the `ThisBuild` scope). Shoulda read through sbt-sonatype repo a bit more, sorry for troublin' ya
