### ISSUE TITLE
Release succeeded but not publically available

### ISSUE THREAD

**Issue by bbstilson** [sbt/sbt-ci-release#237]
Hello team,

I'm the maintainer of the [sbt-codeartifact](https://github.com/bbstilson/sbt-codeartifact) plugin, and a recent patch release (0.2.4) succeeded according to this plugin, but it never became publicly available.

You can see the successful build output [here](https://github.com/bbstilson/sbt-codeartifact/runs/5844933389?check_suite_focus=true#step:5:153), and I see the files on Sonatype:

![image](https://user-images.githubusercontent.com/7949037/162523255-b98efb0d-288f-4f83-963d-8eb0e8003547.png)

But this version hasn't appeared on [Maven central](https://repo1.maven.org/maven2/io/github/bbstilson/sbt-codeartifact_2.12_1.0/).

I suspect this isn't an issue with this plugin but I'm not really sure how to troubleshoot this issue. Any advice would be greatly appreciated 🙂

**Comment by eed3si9n** [comment]
I'd recommend contacting Sonatype via https://issues.sonatype.org/secure/Dashboard.jspa and explain your issue there. They have the power to fix this (not us), and they're usually really helpful in these matters.
