### ISSUE TITLE
Support for Sonatype Central

### ISSUE THREAD

**Issue by KacperFKorban** [sbt/sbt-ci-release#294]
It seems that Sonatype's Jira is being deprecated in favour of [Sonatype Central](https://central.sonatype.com/). ([docs](https://central.sonatype.org/register/central-portal/)) The intention is to make Sonatype Central the main/only way to publish artifacts. It would be great to be able to publish to Sonatype Central using `sbt-ci-release`

There already exists a PR with the support for Sonatype Central API in `sbt-sonatype`: https://github.com/xerial/sbt-sonatype/pull/474

**Comment by Andrapyre** [comment]
Refactoring here should be very minimal, once `sbt-sonatype` has a new release, as the current implementation in [this PR](https://github.com/xerial/sbt-sonatype/pull/474) supports running `sonatypeBundleRelease` to deploy artifacts to Sonatype Central.

Sonatype Central does not support publishing snapshots however, so any logic around snapshot publication will need to be refactored, but that, again, looks very minimal.

**Comment by KacperFKorban** [comment]
> Refactoring here should be very minimal, once sbt-sonatype has a new release, as the current implementation in https://github.com/xerial/sbt-sonatype/pull/474 supports running sonatypeBundleRelease to deploy artifacts to Sonatype Central.

I thought as much. I think that the `sbt-ci-release` documentation might require the most changes. It is linked in many other repositories and is considered a "Scala Sonatype publishing" source of truth.

BTW, thanks for implementing https://github.com/xerial/sbt-sonatype/pull/474 :heart:

**Comment by Andrapyre** [comment]
Good point about reproducing sonatype docs here, though I also don't see that requiring much investment, as the current implementation just requires users to change the sonatype host in order for everything to work out of the box.

**Comment by xuwei-k** [comment]
- https://github.com/sbt/sbt-ci-release/pull/298

**Comment by eed3si9n** [comment]
https://github.com/sbt/sbt-ci-release/pull/303 landed, but given https://github.com/xerial/sbt-sonatype/issues/507 we might need to update.

**Comment by mbaechler** [comment]
> Good point about reproducing sonatype docs here, though I also don't see that requiring much investment, as the current implementation just requires users to change the sonatype host in order for everything to work out of the box.

Hi @Andrapyre, I'm trying to make use of `sbt-ci-release` to publish my lib and I may not understand what you mean by 

> requires users to change the sonatype host in order for everything to work out of the box

Are you referring to something like
```
ThisBuild / sonatypeCredentialHost := sonatypeCentralHost
```

Maybe I did a stupid mistake but I can't make it work, I always get "Repository for publishing is not specified."

For reference, the project is here https://github.com/PerformanceIMMO/pg-event-store and the failing publish logs are here https://github.com/PerformanceIMMO/pg-event-store/actions/runs/10847421290/job/30102632825

Thanks for your help.

**Comment by Andrapyre** [comment]
@mbaechler , the link is coming up as not found for some reason. Is this a private repo?

**Comment by mbaechler** [comment]
@Andrapyre yes, sorry, it was public by mistake.
