### ISSUE TITLE
Mention in the docs the Sonatype user tokens might contain special characters

### ISSUE THREAD

**Issue by bcarter97** [sbt/sbt-ci-release#309]
After switching to the new User tokens I spent a few hours banging my head trying to figure out what I'd done wrong. Using Travis I already had my passphrase quoted, I didn't expect the username to contain special characters and overlooked it as the cause. It might be worth adding a tiny note to the docs for this? If so I can raise a PR

**Comment by eed3si9n** [comment]
Doesn't it already say

> SONATYPE_PASSWORD: The password you use to log into https://s01.oss.sonatype.org/ (or https://oss.sonatype.org/ if your Sonatype account was created before February 2021). Alternatively, the password part of the user token if you generated one above. For Travis Only: If the password contains bash special characters, make sure to escape it by wrapping it in single quotes 'my?pa$$word', see [Travis Environment Variables](https://docs.travis-ci.com/user/environment-variables/#defining-variables-in-repository-settings).

**Comment by bcarter97** [comment]
It does indeed, but I didn't consider the user token "user" it generates could contain special characters too, and overlooked this

**Comment by eed3si9n** [comment]
I see. the token user name not the password. Feel free to send a PR to improve the doc on this.

**Comment by bcarter97** [comment]
I have raised https://github.com/sbt/sbt-ci-release/pull/310
