### ISSUE TITLE
sbt 2.0 cross-builds

### ISSUE THREAD

**Issue by BillyAutrey** [sbt/sbt-ci-release#314]
Because `sbt-ci-release` pulls in plugins via addSbtPlugin, as far as I can tell it forces this plugin to require crossbuilds of the downstream plugins as well.

This means we'll need 2.0.0-M2 crossbuilds of:

* `sbt-dynver` 
  * https://github.com/sbt/sbt-dynver/issues/308
  * wip in https://github.com/sbt/sbt-dynver/pull/305
* `sbt-git` 
  * https://github.com/sbt/sbt-git/issues/257
  * Available in [`2.1.0`](https://github.com/sbt/sbt-git/releases/tag/v2.1.0)
* `sbt-sonatype`
  * https://github.com/xerial/sbt-sonatype/issues/523
  * Available in [`3.12.0`](https://github.com/xerial/sbt-sonatype/releases/tag/v3.12.0)
* `sbt-pgp` - ✅ 
  * https://github.com/sbt/sbt-pgp/pull/214 - `2.3.0`
  * https://github.com/sbt/sbt-ci-release/pull/312

**Comment by xuwei-k** [comment]
- https://github.com/sbt/sbt-ci-release/pull/320#issuecomment-2408906914 🤔

**Comment by eed3si9n** [comment]
@xuwei-k The current version works but in the future it might not support JDK 8? If that happens, I suggest we should fork the plugin to maintain JDK 8 compatibility.
