### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by SethTisue** [sbt/sbt-ci-release#319]
[1.7.0](https://github.com/sbt/sbt-ci-release/releases/tag/v1.7.0) only came out a few days ago, so I'm a bit reluctant to hit the release button again too soon. partly because it's churn and partly because we don't really know yet if 1.7.0 was solid

but since 1.7.0 we've updated sbt-git to [2.1.0](https://github.com/sbt/sbt-git/releases/tag/v2.1.0) which has a really nice performance fix (@adpi's https://github.com/sbt/sbt-git/pull/248) that I'd like to see in everyone's hands

we've also updated sbt-pgp and sbt-sonatype but those seem less significant to me

maybe we should release in a week or so...?

**Comment by SethTisue** [comment]
there's also the question of sbt 2.0 support which is #314 — at the moment that one is waiting on sbt-dynver

**Comment by SethTisue** [comment]
#314 is merged, so I think that's sufficient grounds to roll a release on Monday

**Comment by eed3si9n** [comment]
It's Monday somewhere - https://github.com/sbt/sbt-ci-release/releases/tag/v1.8.0
